### ISSUE TITLE
Android: Crash when switching app after a ViroSceneNavigator is removed from JSX

### ISSUE THREAD

**Issue by ccwai** [viromedia/viro#139]
I have integrated my APP to Viro and I followed [this](https://github.com/viromedia/viro/issues/86) to exit ViroSceneNavigator.
After that, I press Android home button or menu button, the App will then crash and will get this error:

### E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.hktbvrapp, PID: 4089
                  Theme: themes:{}
                  java.lang.RuntimeException: Unable to pause activity {com.hktbvrapp/com.hktbvrapp.MainActivity}: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                      at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3427)
                      at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3386)
                      at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3361)
                      at android.app.ActivityThread.-wrap13(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1374)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5475)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                   Caused by: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                      at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                      at java.util.ArrayList.get(ArrayList.java:308)
                      at com.viromedia.bridge.component.SceneNavigator.onHostPause(SceneNavigator.java:335)
                      at com.viromedia.bridge.component.SceneNavigator.access$300(SceneNavigator.java:34)
                      at com.viromedia.bridge.component.SceneNavigator$SceneNavigatorLifecycleListener.onHostPause(SceneNavigator.java:89)
                      at com.facebook.react.bridge.ReactContext.onHostPause(ReactContext.java:215)
                      at com.facebook.react.ReactInstanceManager.moveToBeforeResumeLifecycleState(ReactInstanceManager.java:628)
                      at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:502)
                      at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:521)
                      at com.facebook.react.ReactActivityDelegate.onPause(ReactActivityDelegate.java:119)
                      at com.facebook.react.ReactActivity.onPause(ReactActivity.java:60)
                      at android.app.Activity.performPause(Activity.java:7237)
                      at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1312)
                      at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3413)
                      at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3386) 
                      at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3361) 
                      at android.app.ActivityThread.-wrap13(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1374) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:5475) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

It seems that after the ViroSceneNavigator is removed from JSX, it still listens to the AppState changed and attempt to pause a scene when AppState is paused.

Is there any workarounds to avoid this?
Many Thanks!

**Comment by achuvm** [comment]
Hi @ccwai,

I was unable to repro this on Viro 2.2.0 on a Pixel 2. I suggest you upgrade to Viro 2.2.0 as it looks like this issue has already been fixed.

Our releases & update instructions are here: https://docs.viromedia.com/docs/releases

Let us know if you need help or run into issues upgrading.

**Comment by ccwai** [comment]
Hi @achuvm ,
Thanks for your help! The new version had fixed this issue.
