### ISSUE TITLE
Not requesting ARCore installation when optional

### ISSUE THREAD

**Issue by draperunner** [viromedia/viro#184]
Hi!

We have an AR feature as part of out app, and have added `<meta-data android:name="com.google.ar.core" android:value="optional" />` to out AndroidManifest.xml. But when we start the AR scene, the app crashes, instead of requesting the install of ARCore. This has been tested on Samsung S7 and S8.

The weird thing is that is had worked before... What has changed?

We are using Viro v2.4.0, and here is the stacktrace:
```
Fatal Exception: com.google.ar.core.exceptions.UnavailableArcoreNotInstalledException
       at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:343)
       at com.google.ar.core.Session.nativeCreateSession(Session.java)
       at com.google.ar.core.Session.<init>(Session.java:87)
       at com.viro.core.ViroViewARCore.init(ViroViewARCore.java:239)
       at com.viro.core.ViroViewARCore.<init>(ViroViewARCore.java:192)
       at com.viromedia.bridge.component.VRTARSceneNavigator.createViroView(VRTARSceneNavigator.java:41)
       at com.viromedia.bridge.component.VRTSceneNavigator.<init>(VRTSceneNavigator.java:148)
       at com.viromedia.bridge.component.VRTARSceneNavigator.<init>(VRTARSceneNavigator.java:23)
       at com.viromedia.bridge.component.VRTARSceneNavigatorManager.createViewInstance(VRTARSceneNavigatorManager.java:28)
       at com.viromedia.bridge.component.VRTARSceneNavigatorManager.createViewInstance(VRTARSceneNavigatorManager.java:15)
       at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:224)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:153)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:813)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:926)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:47)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:986)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:925)
       at android.view.Choreographer.doCallbacks(Choreographer.java:702)
       at android.view.Choreographer.doFrame(Choreographer.java:635)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by draperunner** [comment]
My bad! Seems like Viro 2.3.0 was installed, not 2.4.0. But now it seems like `onTrackingInitialized` never happens, and it does not ask for ARCore installation... We'll look into this tomorrow. I'm closing this issue and opening another one if necessary.
