### ISSUE TITLE
Can not find native methods for ViroCore

### ISSUE THREAD

**Issue by Sovianum** [viromedia/viro#238]
Hello, everyone. I'm sorry if my question sounds stupid, but the problem is follows:
I used virocore [hello world](https://github.com/viromedia/virocore/tree/master/ARHelloWorldAndroid) application to transfer my [ARCore project](https://github.com/Sovianum/arcore-android-sdk) to virocore. 
Hello world successfully compiles and runs on my smartphone (Samsung Galaxy S7 Edge). But when I try to run my application I get an error

`
E/art: No implementation found for long com.viro.core.Node.nativeCreateNode() (tried Java_com_viro_core_Node_nativeCreateNode and Java_com_viro_core_Node_nativeCreateNode__)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.virosample.arcore, PID: 1443
                  java.lang.UnsatisfiedLinkError: No implementation found for long com.viro.core.Node.nativeCreateNode() (tried Java_com_viro_core_Node_nativeCreateNode and Java_com_viro_core_Node_nativeCreateNode__)
                      at com.viro.core.Node.nativeCreateNode(Native Method)
                      at com.viro.core.Node.<init>(Node.java:219)
                      at com.viro.core.Object3D.<init>(Object3D.java:63)
                      at edu.technopark.arquest.core.game.Identifiable3D.<init>(Identifiable3D.java:14)
                      at edu.technopark.arquest.core.game.slot.Slot.<init>(Slot.java:70)
                      at edu.technopark.arquest.core.game.Player.<init>(Player.java:16)
                      at edu.technopark.arquest.quest.game.ActorPlayer.<init>(ActorPlayer.java:7)
                      at edu.technopark.arquest.GameModule.<init>(GameModule.java:40)
                      at edu.technopark.arquest.App.onCreate(App.java:21)
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5885)
                      at android.app.ActivityThread.-wrap3(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6692)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
E/art: No implementation found for void com.viro.core.Node.nativeRemoveTransformDelegate(long, long) (tried Java_com_viro_core_Node_nativeRemoveTransformDelegate and Java_com_viro_core_Node_nativeRemoveTransformDelegate__JJ)
E/art: No implementation found for void com.viro.core.Node.nativeRemoveTransformDelegate(long, long) (tried Java_com_viro_core_Node_nativeRemoveTransformDelegate and Java_com_viro_core_Node_nativeRemoveTransformDelegate__JJ)
E/System: Uncaught exception thrown by finalizer
E/System: java.lang.UnsatisfiedLinkError: No implementation found for void com.viro.core.Node.nativeRemoveTransformDelegate(long, long) (tried Java_com_viro_core_Node_nativeRemoveTransformDelegate and Java_com_viro_core_Node_nativeRemoveTransformDelegate__JJ)
              at com.viro.core.Node.nativeRemoveTransformDelegate(Native Method)
              at com.viro.core.Node.removeTransformListener(Node.java:1620)
              at com.viro.core.Node.dispose(Node.java:268)
              at com.viro.core.Object3D.dispose(Object3D.java:131)
              at com.viro.core.Node.finalize(Node.java:257)
              at com.viro.core.Object3D.finalize(Object3D.java:123)
              at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222)
              at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209)
              at java.lang.Thread.run(Thread.java:762)
Application terminated.
`
Here is the [https://github.com/Sovianum/arcore-android-sdk/blob/use-virocore-instead-direct-arcore/app/src/main/java/edu/technopark/arquest/core/game/Identifiable3D.java#L14](link) to the failing code.

I must note that I have changed the package name from com.example.virosample to edu.technopark.arquest.

Could you explain how I can fix this?

**Comment by Sovianum** [comment]
Finally I found out that the problem was in using library capabilities before creating ViroView as native libraries are loaded during view initialization. So now I am interested: are there any particular reasons to do such loading exactly in the ViroView initialization or is it safe to load these libraries before the first library usage?

**Comment by manbod** [comment]
This was fixed in a later version of ViroCore.
