### ISSUE TITLE
Asset not found: object_car_2.mtl

### ISSUE THREAD

**Issue by pratomchaip** [viromedia/viro#266]
Hi,
I'm trying to run the ARCarDemo on my phone but I'm getting an error: 
```
Error: Asset not found: .../viro/js/ARCarDemo/res/tesla/object_car_2.mtl for platform: null  
    at .../viro/node_modules/metro/src/Assets/index.js:148:13  
    at Generator.next (<anonymous>)  
    at step (.../viro/node_modules/metro/src/Assets/index.js:327:347)
    at .../viro/node_modules/metro/src/Assets/index.js:327:507
    at <anonymous>
```

I've looked around but I can't find a reference to ```/js/ARCarDemo/res/tesla/object_car_2.mtl``` only ```/js/ARCarDemo/res/tesla/object_car.mtl```.

I'm using an iPhone X to run the demo on a the latest Viro Media Testbed app - Version 2.11(1)
Does anyone have this issue too?

**Comment by pratomchaip** [comment]
Didn't find the problem, but as a work around, I got it to work by renaming `.../viro/js/ARCarDemo/res/tesla/object_car.mtl` to `.../viro/js/ARCarDemo/res/tesla/object_car_2.mtl`.

Also, the ARCarDemo needs ARKit 1.5 to run.
