### ISSUE TITLE
 java.lang.RuntimeException: createContext failed: EGL_BAD_CONTEXT

### ISSUE THREAD

**Issue by leocavalcante** [viromedia/viro#33]
```
09-21 17:53:45.852 3615-3720/com.hellovr E/AndroidRuntime: FATAL EXCEPTION: GLThread 31579
                                                           Process: com.hellovr, PID: 3615
                                                           java.lang.RuntimeException: createContext failed: EGL_BAD_CONTEXT
                                                               at com.google.vr.ndk.base.GvrSurfaceView$EglHelper.throwEglException(GvrSurfaceView.java:1226)
                                                               at com.google.vr.ndk.base.GvrSurfaceView$EglHelper.throwEglException(GvrSurfaceView.java:1217)
                                                               at com.google.vr.ndk.base.GvrSurfaceView$EglHelper.start(GvrSurfaceView.java:1051)
                                                               at com.google.vr.ndk.base.GvrSurfaceView$GLThread.guardedRun(GvrSurfaceView.java:1479)
                                                               at com.google.vr.ndk.base.GvrSurfaceView$GLThread.run(GvrSurfaceView.java:1323)
```

React Viro 1.1.0 on Samsung S8

**Comment by achuvm** [comment]
Hi @leocavalcante, 

We just tried a new Hello World Scene with React Viro 1.1.0 on our Samsung S8+ and it works.

So we have a few questions:
- Is your Google VR Services updated to the latest version (via the Play Store)?
- Are you running the Hello World Scene? If not, can you try the Hello World scene?

Thanks,

**Comment by achuvm** [comment]
Closing due to inactivity.

If you still have issues, feel free to re-open this issue or create a new one.

The latest releases are here: 
React Viro - https://docs.viromedia.com/docs/releases
ViroCore - https://virocore.viromedia.com/docs/releases

Thanks for using Viro!
