### ISSUE TITLE
Error when loading build from android studio

### ISSUE THREAD

**Issue by JamesBotterill** [viromedia/viro#344]
I've been testing successfully using the Viro Media and found some crashing issues with my app. 

I've now been trying to packages and run the build using android studio on OSX and I'm getting the following error message 

`07-03 18:01:32.181 30288-30358/com.artest E/unknown:ReactNative: Exception in native call
    java.lang.RuntimeException: Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server.
        at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
        at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:216)
        at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:31)
        at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:234)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1114)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:911)
        at java.lang.Thread.run(Thread.java:764) 
` 
Any Advice?

**Comment by VikAdvani** [comment]
Hi @JamesBotterill, 
This error occurs because assets weren't bundling correctly for a release build. If you are building a release build you'll have to run the following command from your projects root directory (YourProjName/android):

1) './gradlew assembleGvrRelease

This command will bundle the assets in your app properly and should remove the error you are seeing.

If you are building a debug version of your app, then do the following:
1) Make sure you have adb installed. With your phone hooked up to your computer via usb, run 'adb reverse tcp:8081 tcp:8081' on your command line. 

2) Run 'npm start' from the project root directory to start the package server
3) Click the green play button in Android Studio to run your app target. 

More info here: https://docs.viromedia.com/docs/android-distribution
and here: https://docs.viromedia.com/docs/installing-viro-android 

Let us know if you are still running into issues.

**Comment by JamesBotterill** [comment]
thanks, the npm start step isn't outline in your online docs. This resolves the issue

**Comment by dam00n** [comment]
Thanks for that catch @JamesBotterill. We updated the docs to include "npm start" step. Closing this issue.
