### ISSUE TITLE
Facing Issues with starting ViroSample from ViroMedia"Getting Started" page

### ISSUE THREAD

**Issue by Thianzeren** [viromedia/viro#420]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Windows
2. Device OS & Version: IOS 11.4.1
3. Version: ViroReact version "2.10.0", React Native version "^0.57.0"
4. Device(s): IPhone 8 

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.
Hello everyone, sorry if this is a minor issue but I'm facing some issues with the "Getting Started" for ViroReact. I've followed all the steps specified for windows to create the ViroSample but I'm unable to start the project and view it via the Viro Media App on my iPhone. Thank you for your help

The following are the errors I'm facing:

PS E:\ReactNativeProjects\ViroSample> npm start

> ViroSample@0.0.1 start E:\ReactNativeProjects\ViroSample
> node node_modules/react-native/local-cli/cli.js start

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   E:\ReactNativeProjects\ViroSample

Loading dependency graph, done.
error: bundling failed: Error: Cannot find module '@babel/plugin-external-helpers'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (E:\ReactNativeProjects\ViroSample\node_modules\metro\src\reactNativeTransformer.js:15:31)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (E:\ReactNativeProjects\ViroSample\node_modules\pirates\lib\index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (E:\ReactNativeProjects\ViroSample\node_modules\pirates\lib\index.js:88:7)
 BUNDLE  [ios, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1)::ffff:10.124.20.239 - - [20/Sep/2018:07:24:55 +0000] "GET /index.bundle?platform=ios&dev=true HTTP/1.1" 200 - "-" "ViroMediaApp/1 CFNetwork/902.2 Darwin/17.7.0"
 BUNDLE  [ios, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/3)

The errors I see on my phone:

Failed to load bundle(http://10.124.4.113:8081/index.bundle?platform=ios&dev=true) with error:(E:\ReactNativeProjects\ViroSample\node_modules\react-native\Libraries\react-native\react-native-implementation.js: Cannot find module '@babel/plugin-external-helpers' (null))

void google::protobuf::internal::arena_delete_object<vr::internal::widgets::video::SphericalMetadata>(void*)
    RCTCxxBridge.mm:420
void google::protobuf::internal::arena_delete_object<vr::internal::widgets::video::SphericalMetadata>(void*)
void google::protobuf::internal::arena_delete_object<vr::internal::widgets::video::SphericalMetadata>(void*)
void google::protobuf::internal::arena_delete_object<vr::internal::widgets::video::SphericalMetadata>(void*)
void google::protobuf::internal::arena_delete_object<vr::internal::widgets::video::SphericalMetadata>(void*)
void google::protobuf::internal::arena_delete_object<vr::internal::widgets::video::SphericalMetadata>(void*)

> <redacted
> <redacted
> <redacted
> <redacted
> <redacted
> <redacted
> <redacted
> <redacted
> <redacted
> <redacted
> <redacted
> <redacted
> <redacted
> <redacted
> <redacted

_pthread_wqthread
start_wqthread

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, screen capture, video recording. The more information you provide, the better we can support you.

I followed the steps exactly from this page:
https://docs.viromedia.com/docs/quick-start-windows

**Comment by Thianzeren** [comment]
Sorry for the issue, just realised that the react native version of 0.57 is not supported by ViroReact yet
