### ISSUE TITLE
java.lang.AbstractMethodError: abstract method "java.util.List com.facebook.react.ReactPackage.createJSModules()"

### ISSUE THREAD

**Issue by alesanderlopez** [viromedia/viro#421]
## Environment
1. Development OS: 
```
MacOS High Sierra 10.13.6 (17G65) / Macbook Pro 2016  (1st generation touch bar)
Android Studio 3.1.3
Gradle 2.2.3
```
2. Device OS & Version: Android some versions: 
```
Android 7.1.2
```
3. Version: 
```json
"react-native": "0.46.4",
"react": "16.0.0-alpha.12",
"react-viro": "^2.0.0"
```
4. Device(s): What device(s) are you are seeing the issue on (i.e. iPhone X, Samsung Note 8, etc)
```
Emulator with many android versions, 
Samsung Galaxy S3, 
Xiaomi Redmi Note 3, 
Samsung Galaxy Tab 3, 
Bq Acuarius
```

## Description
Hello, i'm trying to make a apk build in Android but always i have problems. I'm using 2.0.0 Viromedia library because i had some issues in Xcode with the nexts versions from React-native old lib's.

```log
09-22 13:19:51.932 32269-32292/com.museogaldar W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.viromedia.bridge.component.SoundManager
09-22 13:19:51.937 32269-32292/com.museogaldar W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.viromedia.bridge.component.SoundFieldManager
09-22 13:19:51.940 32269-32292/com.museogaldar W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.viromedia.bridge.component.SpatialSoundManager
09-22 13:19:51.945 32269-32292/com.museogaldar W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.viromedia.bridge.component.node.control.TextManager
09-22 13:19:51.949 32269-32292/com.museogaldar W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.viromedia.bridge.component.node.control.Object3dManager
09-22 13:19:51.952 32269-32292/com.museogaldar W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.viromedia.bridge.component.ControllerManager
09-22 13:19:51.956 32269-32292/com.museogaldar W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.viromedia.bridge.component.node.control.PolylineManager
09-22 13:19:51.959 32269-32292/com.museogaldar W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.viromedia.bridge.component.ar.ARNavigatorManager
09-22 13:19:51.960 32269-32292/com.museogaldar W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.BV.LinearGradient.LinearGradientManager
09-22 13:19:52.119 32269-32292/com.museogaldar E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: com.museogaldar, PID: 32269
    java.lang.AbstractMethodError: abstract method "java.util.List com.facebook.react.ReactPackage.createJSModules()"
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1011)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:944)
        at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:109)
        at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:743)
        at java.lang.Thread.run(Thread.java:761)
```

## Reproducible Demo
App build.gradle 
```gradle
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.1"


    /**
    dexOptions {
        jumboMode true
    }
    */

    defaultConfig {
        multiDexEnabled true
        applicationId "com.museogaldar"
        minSdkVersion 23
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }

    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
...

dependencies {
    compile 'com.android.support:appcompat-v7:25.0.1'
    compile 'com.facebook.react:react-native:+'
    //compile project(':arcore_client') // remove this if AR not required
    compile project(':gvr_common')
    compile project(path: ':viro_renderer')
    compile project(path: ':react_viro')
    compile 'com.google.android.exoplayer:exoplayer:2.7.1'
    compile 'com.google.protobuf.nano:protobuf-javanano:3.0.0-alpha-7'
    compile 'com.amazonaws:aws-android-sdk-core:2.2.+'
    compile 'com.amazonaws:aws-android-sdk-ddb:2.2.+'
    compile 'com.amazonaws:aws-android-sdk-ddb-mapper:2.2.+'
    compile 'com.amazonaws:aws-android-sdk-cognito:2.2.+'
    compile 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.2.+'
}
```
Project build.gradle
```gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
            maven { url 'https://maven.google.com' }
        }
    }
}
```

settings.gradle
```gradle
include ':react_viro', ':arcore_client', ':gvr_common', ':viro_renderer'
project(':arcore_client').projectDir = new File('../node_modules/react-viro/android/arcore_client')
project(':gvr_common').projectDir = new File('../node_modules/react-viro/android/gvr_common')
project(':viro_renderer').projectDir = new File('../node_modules/react-viro/android/viro_renderer')
project(':react_viro').projectDir = new File('../node_modules/react-viro/android/react_viro')
include ':app'
```

MainApplication.java
```java
import com.viromedia.bridge.ReactViroPackage;
...
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new ReactNativeAudioStreamingPackage(),
            new MapsPackage(),
            new RNFetchBlobPackage(),
            new PhotoViewPackage(),
            new ReactViroPackage(ReactViroPackage.ViroPlatform.GVR),
            new LinearGradientPackage(),
            new VectorIconsPackage()
      );
    }
```

**Comment by VikAdvani** [comment]
Hi @alesanderlopez, React viro doesn't work currently on the Android emulator. Are you getting the same issue on an Android device as well?

**Comment by alesanderlopez** [comment]
Hi @VikAdvani yes unfortunately i have the same issue in Android devices :/

**Comment by VikAdvani** [comment]
Hi @alesanderlopez, react-viro 2.0 is compatible with react native  v0.47.2 not react native react-native": "0.46.4", which you are currently using. 

There was a breaking change with react-native 0.47 with relation to createJSModules. I'm guessing that perhaps react-viro 2.0.0 implements the creation of a react native package with the new 0.47 way leading to your error, since you are using 0.46.4.

Thread here: https://github.com/realm/realm-js/issues/1176

If you upgrade to the compatible RN version(0.47.2) do you still get this error?

**Comment by dam00n** [comment]
Closing issue due to inactivity. Please re-open if you are still experiencing this problem and can provide more info
