### ISSUE TITLE
Warning: Native component for "VRTSceneNavigator" does not exist

### ISSUE THREAD

**Issue by frayeralex** [viromedia/viro#50]
When i try to run app on device or emulator i see
![screen shot 2017-10-13 at 10 25 57](https://user-images.githubusercontent.com/15966404/31534748-eb6c0c02-b000-11e7-9555-6b456d1c8605.png)
![screen shot 2017-10-13 at 10 26 41](https://user-images.githubusercontent.com/15966404/31534816-3622af3a-b001-11e7-8767-bf83802296cc.png)

**Comment by VikAdvani** [comment]
Hi, @frayeralex, 
1)To get rid of the warnings run the script setup-ide.sh in the root directory of the project. This will properly link react-viro with your ios and android project. 

2)Regarding the emulator, react-viro currently doesn't work in the emulator. You'll need to build to an ios or android device.

Let me know if you have any more questions. Also, here's a full guide to get xcode up and running:
 http://docs.viromedia.com/docs/starting-a-new-viro-project-1

**Comment by achuvm** [comment]
Closing due to inactivity.

If you still have issues, feel free to re-open this issue or create a new one.

The latest releases are here:
React Viro - https://docs.viromedia.com/docs/releases
ViroCore - https://virocore.viromedia.com/docs/releases

Thanks for using Viro!

**Comment by dokwon** [comment]
@VikAdvani followed your first suggestion above, results in: 

Task 'installDebug' not found in root project 'ViroSample'. Some candidates are: 'installGvrDebug', 'installOvrDebug'.

**Comment by achuvm** [comment]
Hi @dokwon,

It sounds like you're building from command line? If so, then you'll have to use either 'installGvrDebug' or 'installOvrDebug' because our setup-ide.sh script adds 2 build flavors. You should use the Gvr flavor if you want anything other than Oculus VR for Gear VR.

**Comment by dokwon** [comment]
I ran 

'gradle installGvrDebug' 

and got the following error: 


Caused by: java.lang.NoSuchMethodError: com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V
        at com.android.build.gradle.tasks.factory.JavaCompileConfigAction.execute(JavaCompileConfigAction.java:131)
        at com.android.build.gradle.tasks.factory.JavaCompileConfigAction.execute(JavaCompileConfigAction.java:39)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:148)
        at com.android.build.gradle.internal.TaskContainerAdaptor.create(TaskContainerAdaptor.java:59)
        at com.android.build.gradle.internal.scope.AndroidTaskRegistry.create(AndroidTaskRegistry.java:47)
        at com.android.build.gradle.internal.scope.AndroidTaskRegistry.create(AndroidTaskRegistry.java:89)
        at com.android.build.gradle.internal.TaskManager.createJavacTask(TaskManager.java:1102)
        at com.android.build.gradle.internal.ApplicationTaskManager$13.call(ApplicationTaskManager.java:248)
        at com.android.build.gradle.internal.ApplicationTaskManager$13.call(ApplicationTaskManager.java:241)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
        at com.android.build.gradle.internal.ApplicationTaskManager.createTasksForVariantData(ApplicationTaskManager.java:238)
        at com.android.build.gradle.internal.VariantManager.createTasksForVariantData(VariantManager.java:485)
        at com.android.build.gradle.internal.VariantManager$3.call(VariantManager.java:293)
        at com.android.build.gradle.internal.VariantManager$3.call(VariantManager.java:290)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
        at com.android.build.gradle.internal.profile.SpanRecorders.record(SpanRecorders.java:44)
        at com.android.build.gradle.internal.VariantManager.createAndroidTasks(VariantManager.java:286)
        at com.android.build.gradle.BasePlugin$11.call(BasePlugin.java:688)
        at com.android.build.gradle.BasePlugin$11.call(BasePlugin.java:685)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
        at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:683)
        at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:608)
        at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:605)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
        at com.android.build.gradle.BasePlugin.lambda$createTasks$1(BasePlugin.java:603)
        at com.android.build.gradle.BasePlugin$$Lambda$127/1154582025.execute(Unknown Source)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
        ... 88 more

**Comment by achuvm** [comment]
Hi @dokwon,

Assuming you've created a React Viro project and have run `setup-ide.sh --android` from within your React Viro project (if you haven't follow the steps in our [quick start](https://docs.viromedia.com/docs/quick-start) and our [Android Studio setup guide](https://docs.viromedia.com/docs/installing-viro-android)), try the following steps:

`cd <your_project>/android`
`./gradlew installGvrDebug`

that should build & install the `debug` apk to your device, however to use the application, you need to set up 1) your packager server and 2) reverse TCP to tether your device to your laptop.

To start your packager server, simply run the following commands:
`cd <your_project>`
`npm start`

In another terminal window, run the follow command:
`adb reverse tcp:8081 tcp:8081`

Then start the app you previously installed on your device, after accepting the permissions (React Native requires the "draw over other apps" permission for its debug menu) a red bar should appear at the top as the JS files are transferred over the tethered connection you set up with the adb command.

To make changes in JS, simply make the changes, and either "shake" the device and tap reload, or from the terminal type `adb shell input text 'rr'`.

--

Alternatively, you can simply build in `release`, but it'll take longer as it has to bundle the JS files & resources. 

To do this, simply run:

`cd <your_project>/android`
`./gradlew installGvrRelease`

Then simply launch the app. The packager server and reverse tethering isn't needed in this case because the app is in release mode w/ all the JS assets/code bundled in the APK itself.

--

Finally, it's strange that you couldn't find the `installGvrDebug` gradle task above. To see all the available gradle tasks, you can run `gradle tasks` (or `./gradlew tasks` if you have a gradle wrapper, like in our project).

Let us know if you have any other questions or run into any issues with the above instructions!

Andy

**Comment by dokwon** [comment]
A couple of clarifications: 

1. react-native run-android (which equates to cd android && gradlew installDebug) could not find the build flavor installDebug, not installGvrDebug.

2. The 'setDependencyCacheDir' issue I highlighted in my second comment occurs when I follow all the steps you outlined above. After some googling, I discovered that some react native projects are not compatible with the newer versions of gradle. See this related issue in a different project: https://github.com/oblador/react-native-keychain/issues/68

I followed the solution outlined in the link I shared, and the project builds fine. 

Instead of building ViroSample, if I wanted to add ViroReact to one of my own projects, do I simply copy over setup_ide.sh to the root directory of my project and run it? Or do I need to perform additional configuration besides?

**Comment by achuvm** [comment]
Hi @dokwon,

In response to your clarifications:

1) Ahh, yes, because we have multiple product flavors the "default" `installDebug` task is not available and so, the `react-native run-android` command won't work.

2) Interesting, thanks for bringing this to our attention. We'll try to repro the issue with a new version of gradle and we'll add a bug to our backlog.

I wouldn't copy over `setup_ide.sh` because it's got a few "hardcoded" line numbers and such. However, we do have instructions on how to add React Viro to an existing Android project [here](https://docs.viromedia.com/docs/integrating-existing-projects-android) which is exactly what the script does itself.

Thanks again and feel free to reach out if you run into any issues.

Andy
