### ISSUE TITLE
Bundling error relating to Cache.set

### ISSUE THREAD

**Issue by danielvarcas** [viromedia/viro#515]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Linux
2. Device OS & Version: Android version 9
3. Version: ViroReact version and React Native version 
4. Device(s): Pixel 2

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.

I am using the ViroSample project. I run `npm start` and enter the testbed on my device.  I then get a red screen error message saying the dev server returned error code 5400 and to look at the terminal for more details.  The terminal outputs the following:

```
 BUNDLE  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/
1)::ffff:127.0.0.1 - - [18/Jan/2019:22:24:24 +0000] "GET /index.delta?platform=android&dev=true&minify=false HTTP/1.1" 5error: bundling failed: Error: EACCES: permission denied, op
en '/tmp/metro-cache/c1/13069d0102df69b997f7780b119cf56a7c722e9a3072f72afdfe43732740484940c5fc'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at FileStore.set (/[REDACTED]/ViroSample/node_modules/metro-cache/src/stores/FileStore.js:37:8)
    at Cache.set (/[REDACTED]/ViroSample/node_modules/metro-cache/src/Cache.js:122:31)
    at /[REDACTED]/ViroSample/node_modules/metro/src/DeltaBundler/Transformer.js:181:13
    at Generator.next (<anonymous>)
    at step (/[REDACTED]/ViroSample/node_modules/metro/src/DeltaBundler/Transformer.js:31:30)
    at /[REDACTED]/ViroSample/node_modules/metro/src/DeltaBundler/Transformer.js:42:15
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

If I go to `/src/Components/Transformer.js` line 181 and delete `cache.set(fullKey, data.result)`, I can get the demo app to run fine. However, as a beginner, I don't want to take lines of code out when I don't know what they're doing and particularly not when this is Viro's sample project.

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, screen capture, video recording. The more information you provide, the better we can support you.

As above.

**Comment by VikAdvani** [comment]
Hi @danielvarcas, 
This seems to be system config issue looking at the error. The metro bundler doesn't have user permissions to the tmp directory or specifically the file _'/tmp/metro-cache/c1/13069d0102df69b997f7780b119cf56a7c722e9a3072f72afdfe43732740484940c5fc'_
causing your error.

This means the user login that you are using on your machine doesn't have proper access. You can try running the bundler with 'sudo' or perhaps configure metro to use a different directory for the cache(one you have access to):

Metro caching docs:
https://facebook.github.io/metro/docs/en/caching
