### ISSUE TITLE
VR Image360 crash Android 5.1.1

### ISSUE THREAD

**Issue by cristianoccazinsp** [viromedia/viro#615]
Having the following crash on an Low end Android device: Samsung Grand Prime, Android 5.1.1
 Any ideas? Not OOM, just a GL crash... Quite hard to debug. Crash happens only when rendering the 360 Image.

"react": "16.8.6",
"react-native": "^0.59.5",
"react-viro": "2.14.0",

```
function GetViroScene(props){
     <ViroScene>
      <Viro360Image
        source={{uri: props.uri}} // props.uri is file://some/local/path
      />
    </ViroScene>
}

<ViroVRSceneNavigator
    apiKey={conf.VIRO_API_KEY}
    vrModeEnabled={false}
    initialScene={{ scene: GetViroScene }}
    passProps={{uri: this.state.modalVisible.uri}}
  />
```

```
05-04 02:08:21.732 32411-502/com.zinspector_rn I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
    (HTTPLog)-Static: isShipBuild true
    (HTTPLog)-Thread-6434-978785533: SmartBonding Enabling is false, SHIP_BUILD is true, log to file is false, DBG is false
    (HTTPLog)-Thread-6434-978785533: SMARTBONDING_FEATURE_ENABLED is false
    (HTTPLog)-Static: isSBSettingEnabled false
05-04 02:08:21.792 32411-32411/com.zinspector_rn D/GvrLayoutFactory: Loaded GvrLayout from SDK.
05-04 02:08:21.872 32411-32411/com.zinspector_rn W/Viro: Attempted to add font [file: SamsungKorean-Bold.ttf, typeface: SamsungKorean] to font family with typeface [SamsungKorean.ttf] -- typefaces do not match, font will be ignored
05-04 02:08:21.922 32411-32411/com.zinspector_rn W/libOpenSLES: class OutputMix interface 0 requested but unavailable MPH=28
05-04 02:08:22.242 32411-32411/com.zinspector_rn D/PhoneWindow: *FMB* installDecor mIsFloating : false
    *FMB* installDecor flags : -2139029248
05-04 02:08:22.312 32411-32411/com.zinspector_rn D/PhoneWindow: *FMB* isFloatingMenuEnabled mFloatingMenuBtn : null
    *FMB* isFloatingMenuEnabled return false
05-04 02:08:22.332 32411-610/com.zinspector_rn D/CognitoCachingCredentialsProvider: Loading credentials from SharedPreferences
    No valid credentials found in SharedPreferences
05-04 02:08:22.342 32411-610/com.zinspector_rn I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
05-04 02:08:22.543 32411-32411/com.zinspector_rn I/Choreographer: Skipped 75 frames!  The application may be doing too much work on its main thread.
05-04 02:08:22.553 32411-510/com.zinspector_rn E/AndroidRuntime: FATAL EXCEPTION: GLThread 6439
    Process: com.zinspector_rn, PID: 32411
    java.lang.IllegalArgumentException: eglChooseConfig failed
        at android.opengl.GLSurfaceView$BaseConfigChooser.chooseConfig(GLSurfaceView.java:861)
        at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1032)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1409)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
05-04 02:08:22.593 32411-32411/com.zinspector_rn D/DisplayManager: addAllDisplaysLocked()
05-04 02:08:22.673 32411-32411/com.zinspector_rn D/SensorManager: unregisterListener ::   
05-04 02:08:24.444 32411-32411/com.zinspector_rn D/ReactNative: ReactInstanceManager.detachViewFromInstance()
```

**Comment by Ashkan-Oliaie** [comment]
I couldn't get it to work also , I tested it on Samsung S4 and it didn't work after loading up the Scenenavigator and first 360 image it gives me the error "unfortunately gvrdebug stopped working"
