### ISSUE TITLE
Multiple screenshots cause OOM

### ISSUE THREAD

**Issue by juspky** [viromedia/viro#636]
## Environment
Please provide the following information about your environment:
1. Windows
2. OnePlus 5 Android Pie

## Description
When taking many screenshots in a short time the app runs out of memory when processing the Screenshot.

```
05-22 11:03:05.931  8633  8633 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 8294419 byte allocation with 5089336 free bytes and 4MB until OOM, max allowed footprint 536870912, growth limit 536870912
05-22 11:03:05.931  8633  8633 E AndroidRuntime:        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
05-22 11:03:05.931  8633  8633 E AndroidRuntime:        at java.nio.DirectByteBuffer$MemoryRef.<init>(DirectByteBuffer.java:71)
05-22 11:03:05.931  8633  8633 E AndroidRuntime:        at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:257)
05-22 11:03:05.931  8633  8633 E AndroidRuntime:        at com.viro.core.ViroMediaRecorder$ScreenShotRunnable.<init>(ViroMediaRecorder.java:662)
05-22 11:03:05.931  8633  8633 E AndroidRuntime:        at com.viro.core.ViroMediaRecorder.takeScreenShotAsync(ViroMediaRecorder.java:617)
05-22 11:03:05.931  8633  8633 E AndroidRuntime:        at com.viromedia.bridge.module.ARSceneNavigatorModule$3$2.onRequestPermissionsResult(ARSceneNavigatorModule.java:204)
05-22 11:03:05.931  8633  8633 E AndroidRuntime:        at com.viromedia.bridge.module.ARSceneNavigatorModule.checkPermissionsAndRun(ARSceneNavigatorModule.java:299)
05-22 11:03:05.931  8633  8633 E AndroidRuntime:        at com.viromedia.bridge.module.ARSceneNavigatorModule.access$000(ARSceneNavigatorModule.java:38)
05-22 11:03:05.931  8633  8633 E AndroidRuntime:        at com.viromedia.bridge.module.ARSceneNavigatorModule$3.execute(ARSceneNavigatorModule.java:201)
```

Check https://stackoverflow.com/a/32245018 for info on that topic.

**Comment by dthian** [comment]
Hey @juspky, what do you mean by "taking many screenshots in a short time". To get more context, what are you trying to achieve here?

**Comment by juspky** [comment]
We got an API that returns position of specific parts of an Image.

I've been given the task to make a sample AR app that sends as many screenshots as possible to that API,  hitTests the returned positions and puts the information in AR space. 

Spamming screenshots is necessary to decrase errors in the image detection and to detect new parts as you move.

This usually works quite good but the app crashes seemingly random with above error.
(As in the app sometimes runs flawlessy for more than 10 minutes, sometimes it runs oom in around 20 seconds)
