### ISSUE TITLE
Android release build crashes when opening ARScene

### ISSUE THREAD

**Issue by ezhilkumaranPE** [viromedia/viro#688]
## Environment

1. Development OS: Mac
2. Device OS & Version: Android OS version ( 8.0, 9)  
3. Version: ViroReact 2.14.0 and React Native 0.59.4 
4. Device(s): Samsung S7 & Google Pixel 2 XL

## Description
I'm getting the below issue when I try to open an ARScene in Android release build. I am not using the 'onTrackingUpdated' method at all.

2019-08-05 11:27:29.851 15376-15376/? E/Viro: ERROR: [/Users/manish/workspace/ViroRenderer/android/app/../../ViroRenderer/VROPlatformUtil.h: VROPlatformCallHostFunction(), line 300]
    ERROR: Unable to find method onTrackingUpdated callback.
2019-08-05 11:27:29.852 15376-15376/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp.sample, PID: 15376
    java.lang.NoSuchMethodError: no non-static method "Lcom/viro/core/ARScene;.onTrackingUpdated(II)V"
        at com.viro.core.internal.PlatformUtil.runTask(Native Method)
        at com.viro.core.internal.PlatformUtil.access$000(PlatformUtil.java:58)
        at com.viro.core.internal.PlatformUtil$TaskRunnable.run(PlatformUtil.java:78)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

In Debug build it works fine and I'm able to load a 3D model successfully. The issue happens only in Android Release build.

**Comment by ChauVV** [comment]
i have same issue!
any help!
