### ISSUE TITLE
Android release build crashes when ViroARScene is rendered

### ISSUE THREAD

**Issue by danivdwerf** [viromedia/viro#716]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: MacOS Mojave(10.14.6)
2. Device OS & Version: Android 8.1.0, iOS 12.4.1
3. Version: ViroReact 2.16.0, React Native 0.60.4 
4. Device(s): Android Galaxy J5(SM-J530F)

## Description
I am using ViroReact for a scene showing a obj file. Everything worked fine on development builds, but the app crashes when I make a release build. It still works perfectly on iOS after a release build. 

I've tried removing everything from the ViroARScene, but it still crashes if I render an empty Scene. If I replace the Scene with a View, I doesn't crash so ViroARSceneNavigator works well.
I removed everything, Animations, Materials, models, lights and have a empty class that does nothing be return an ViroARScene in the render functions and it still crashes.

I get the following log from running $adb logcat -d:
> 09-05 11:27:43.028  1019  1180 D SoLoader: libnative-imagetranscoder.so not found on /data/data/com.studioparkers.brainapp/lib-main
09-05 11:27:43.028  1019  1180 D SoLoader: libnative-imagetranscoder.so found on /data/app/com.studioparkers.brainapp-scjjlJdA2LlK6xQ8tNM5PQ==/lib/arm
09-05 11:27:43.029  1019  1180 D SoLoader: Not resolving dependencies for libnative-imagetranscoder.so
09-05 11:27:43.031  1019  1180 D SoLoader: Loaded: libnative-imagetranscoder.so
09-05 11:27:43.077  4304  4440 D WifiTrafficPoller: TrafficStats TxPkts=19080 RxPkts=29990 TxBytes=2132451 RxBytes=33942640 , Foreground uid=10213 pkgName=com.studioparkers.brainapp txBytes=12946 rxBytes=318431
09-05 11:27:43.179  1019  1025 I zygote  : Do partial code cache collection, code=124KB, data=88KB
09-05 11:27:43.182  1019  1025 I zygote  : After code cache collection, code=116KB, data=83KB
09-05 11:27:43.182  1019  1025 I zygote  : Increasing code cache capacity to 512KB
09-05 11:27:43.541  1019  1062 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.viromedia.bridge.component.VRTViroViewGroupManager$a
09-05 11:27:43.584  1019  1019 D AndroidRuntime: Shutting down VM
09-05 11:27:43.585  1019  1019 E AndroidRuntime: FATAL EXCEPTION: main
09-05 11:27:43.585  1019  1019 E AndroidRuntime: Process: com.studioparkers.brainapp, PID: 1019
09-05 11:27:43.585  1019  1019 E AndroidRuntime: java.lang.IllegalStateException: Unrecognized suffix for the AWS http client class name b
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at e.b.d.g(Unknown Source:54)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at e.b.d.d(Unknown Source:9)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at e.b.d.a(Unknown Source:2)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at e.b.d.a(Unknown Source:7)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at e.b.j.a.b.i(Unknown Source:109)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at e.b.j.a.b.<init>(Unknown Source:8)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at e.b.j.a.b.<init>(Unknown Source:5)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at e.b.j.a.b.<init>(Unknown Source:5)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at e.b.a.s.a(Unknown Source:7)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at e.b.a.s.<init>(Unknown Source:0)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at e.b.a.s.<init>(Unknown Source:11)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at e.b.a.r.<init>(Unknown Source:0)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at com.viro.core.internal.b.f.<init>(Unknown Source:16)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at com.viro.core.ViroView.init(Unknown Source:61)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at com.viro.core.ViroView.<init>(Unknown Source:23)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at com.viro.core.ViroViewARCore.<init>(Unknown Source:0)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at com.viro.core.ViroViewARCore.<init>(Unknown Source:1)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at com.viromedia.bridge.component.i.a(Unknown Source:11)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at com.viromedia.bridge.component.e.<init>(Unknown Source:36)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at com.viromedia.bridge.component.i.<init>(Unknown Source:2)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at com.viromedia.bridge.component.VRTARSceneNavigatorManager.createViewInstance(Unknown Source:2)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at com.viromedia.bridge.component.VRTARSceneNavigatorManager.createViewInstance(Unknown Source:0)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManager.createViewInstanceWithProps(Unknown Source:0)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManager.createViewWithProps(Unknown Source:0)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at com.facebook.react.uimanager.m.a(Unknown Source:34)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at com.facebook.react.uimanager.da$c.execute(Unknown Source:23)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at com.facebook.react.uimanager.ba.run(Unknown Source:46)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at com.facebook.react.uimanager.da.i(Unknown Source:53)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at com.facebook.react.uimanager.da.i(Unknown Source:0)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at com.facebook.react.uimanager.da$f.b(Unknown Source:31)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at com.facebook.react.uimanager.c.a(Unknown Source:0)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at com.facebook.react.modules.core.i$b.a(Unknown Source:52)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at com.facebook.react.modules.core.a.doFrame(Unknown Source:2)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:655)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7000)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
09-05 11:27:43.585  1019  1019 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
09-05 11:27:43.587  4304 14309 D Debug   : !@DumpState : SHIP
09-05 11:27:43.587  4304 14309 D Debug   : !@DumpState : debug level:0x4f4c
09-05 11:27:43.587  4304 14309 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
09-05 11:27:43.587  4304 14309 W ActivityManager: crash : com.studioparkers.brainapp,0
09-05 11:27:43.589  4304 14309 W ActivityManager:   Force finishing activity com.studioparkers.brainapp/.MainActivity
09-05 11:27:43.590  4304 14309 W MultiScreenManagerService: moveTaskBackToDisplayIfNeeded(): root activity or app is null, task=TaskRecord{dd0b3c9 #47 A=com.studioparkers.brainapp U=0 StackId=1 sz=1}, rootActivity=null

## Reproducible Demo
I added ViroReact after I've already started a react-native project, so I haven't used the Viro cli to initialise my project. I have followed (https://docs.viromedia.com/docs/integrating-with-react-native-projects) and everything worked for the development android builds and on iOS. After adding my Keystore and running gradlew assembleRelease the app crashes the moment the ViroARSceneNavigator navigates to the ARScene.

**Comment by JamesRMorey** [comment]
Anyone have any ideas on this i'm also having the same issue
