### ISSUE TITLE
AR crashes

### ISSUE THREAD

**Issue by kaantyy** [viromedia/viro#788]
- [x] Review the documentation: https://docs.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/viro
  - [x] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Mac, Windows, Linux --- **Windows 10**
2. Device OS & Version: What Android OS version (7.0, 8.0, etc.) or iOS version (11.0, 11.2) is your device running on? --- **iOS 13 and Android 9**
3. Version: ViroReact version and React Native version --- **Expo ejected app: react-viro -> 2.17.0 // react-native (sdk 35 -> 0.59.8)**
4. Device(s): What device(s) are you are seeing the issue on (i.e. iPhone X, Samsung Note 8, etc)
**POCOPHONE F1, because on iOS works as expected**
## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.
When click on AR button (to show AR camera), on Android crashes with following errors:
`E/Viro: ERROR: [/Users/manish/tmp-workspace/virocore/android/app/../../ViroRenderer/VROPlatformUtil.h: VROPlatformCallHostFunction(), line 323]
    ERROR: Unable to find method dispatchRenderer callback.
    
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ulbegroup.somoy, PID: 3204
    java.lang.NoSuchMethodError: no non-static method "Lcom/viro/core/internal/PlatformUtil;.dispatchApplication(I)V"
        at com.viro.core.RendererARCore.nativeCreateRendererARCore(Native Method)
        at com.viro.core.RendererARCore.<init>(RendererARCore.java:40)
        at com.viro.core.ViroViewARCore.init(ViroViewARCore.java:562)
        at com.viro.core.ViroViewARCore.<init>(ViroViewARCore.java:465)
        at com.viro.core.ViroViewARCore.<init>(ViroViewARCore.java:437)
        at com.viromedia.bridge.component.VRTARSceneNavigator.createViroView(VRTARSceneNavigator.java:113)
        at com.viromedia.bridge.component.VRT3DSceneNavigator.<init>(VRT3DSceneNavigator.java:183)
        at com.viromedia.bridge.component.VRTARSceneNavigator.<init>(VRTARSceneNavigator.java:91)
        at com.viromedia.bridge.component.VRTARSceneNavigatorManager.createViewInstance(VRTARSceneNavigatorManager.java:47)
        at com.viromedia.bridge.component.VRTARSceneNavigatorManager.createViewInstance(VRTARSceneNavigatorManager.java:34)
        at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:47)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:237)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:200)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:911)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1025)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:46)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1085)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:166)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1063)
        at android.view.Choreographer.doCallbacks(Choreographer.java:877)
        at android.view.Choreographer.doFrame(Choreographer.java:805)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1051)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/Viro: ERROR: [/Users/manish/tmp-workspace/virocore/android/app/../../ViroRenderer/VROPlatformUtil.h: VROPlatformCallHostFunction(), line 323]
    ERROR: Unable to find method dispatchRenderer callback.`

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, screen capture, video recording. The more information you provide, the better we can support you.

**Comment by juancardlm** [comment]
Same error, here.

I found out that setting to false the minifyEnabled parameter on release mode (app/build.gradle), allows you to access to the AR camera, but AR models are not showing.

Still stucked.

**Comment by ChauVV** [comment]
i have same issue!

**Comment by andreatassani** [comment]
hey did you solve it? I have your same issue

**Comment by siddhesh-boppo** [comment]
Add this

 `
buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled  false
            shrinkResources false
        }
    }
`

proguard-rules.pro also can cause issue (if possible remove it)

**Comment by divyangbargali** [comment]
> 

where to add this siddesh-boppo

**Comment by soluelue** [comment]
Add  to proguard-rules.pro 

`-keep class com.viro.** { *; }`
