### ISSUE TITLE
Error: Unable to resolve module `../assets/mug.obj` from `...\src\ARScene.js`: 

### ISSUE THREAD

**Issue by OguzhanArslann** [viromedia/viro#859]
error: bundling failed: Error: Unable to resolve module `../assets//mug.obj` from `c:\Users\OGUZHAN\Desktop\XXX\src\ARScene.js`: The module `../assets//mug.obj` could not be found from `c:\Users\OGUZHAN\Desktop\XXX\src\ARScene.js`. Indeed, none of these files exist:
  * `c:\Users\OGUZHAN\Desktop\XXX\assets\mug.obj(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `c:\Users\OGUZHAN\Desktop\XXX\assets\mug.obj\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (c:\Users\OGUZHAN\Desktop\XXX\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (c:\Users\OGUZHAN\Desktop\XXX\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (c:\Users\OGUZHAN\Desktop\XXX\node_modules\metro\src\node-haste\DependencyGraph.js:283:16)
    at Object.resolve (c:\Users\OGUZHAN\Desktop\XXX\node_modules\metro\src\lib\transformHelpers.js:261:42)
    at dependencies.map.result (c:\Users\OGUZHAN\Desktop\XXX\node_modules\metro\src\DeltaBundler\traverseDependencies.js:399:31)
    at Array.map (<anonymous>)
    at resolveDependencies (c:\Users\OGUZHAN\Desktop\XXX\node_modules\metro\src\DeltaBundler\traverseDependencies.js:396:18)
    at c:\Users\OGUZHAN\Desktop\XXX\node_modules\metro\src\DeltaBundler\traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (c:\Users\OGUZHAN\Desktop\XXX\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
 DELTA  [android, dev] ..\..\../index.js ▓▓▓▓▓▓▓▓▓▓░░░░░░ 68.6% (487/588), failed.

I'm sure to files are in the correct path. What should I do?

![j42sda56hpng](https://user-images.githubusercontent.com/45300385/82162955-a6e65380-98b0-11ea-8dbf-b0d787dc4b90.png)

`<Viro3DObject
            scale={[0.001, 0.001, 0.001]}
            source={require('../assets/mug.obj')}
            rotation={[0, -90, 0]}
            type="OBJ"
            highAccuracyEvents={true}
            animation={{name:"scaleCar", run:this.state.animateCar}}
 />`

**Comment by OguzhanArslann** [comment]
I solved the problem by adding the following line to metro-config.cli : 

```
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 *
 * React Native CLI configuration file
 */
'use strict';

const { getDefaultConfig } = require("metro-config");

module.exports = (async () => {
  const {
    resolver: { assetExts }
  } = await getDefaultConfig();

  return {
    resolver: {
      assetExts: [...assetExts, "obj", "mtl", "JPG", "vrx", "hdr", "gltf", "glb", "bin", "arobject", "gif"]
    }
  };
})();
```

**Comment by MokaCap** [comment]
Hi, I am having the same problem, can you kindly let me where to find the metro-config.cli file? I have looked every where in my project folder but I can't find it. And if I were to create it myself where should I place the file?

Any help would be greatly appreciated!
