### ISSUE TITLE
sceneNavigator.takeScreenshot crashes the app (Android only)

### ISSUE THREAD

**Issue by CommonPlayer** [viromedia/viro#881]
- [ x ] Review the documentation: https://docs.viromedia.com/
  - [ x ] Search for existing issues: https://github.com/viromedia/viro
  - [ x ] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Mac, Windows, Linux
**Windows**
2. Device OS & Version: What Android OS version (7.0, 8.0, etc.) or iOS version (11.0, 11.2) is your device running on?
**Android version 10**
3. Version: ViroReact version and React Native version 
**ViroReact 2.17.0, RN 0.59.3**
4. Device(s): What device(s) are you are seeing the issue on (i.e. iPhone X, Samsung Note 8, etc)
**Nokia 6.1**

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.
calling this.props.sceneNavigator.takeScreenshot("viroScreenshot", true) crashes the app with error message
2020-07-02 18:56:26.697 26142-26142/com.test2_viroar E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test2_viroar, PID: 26142
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/content/ContextCompat;
        at com.viromedia.bridge.module.ARSceneNavigatorModule.hasRecordingPermissions(ARSceneNavigatorModule.java:346)
        at com.viromedia.bridge.module.ARSceneNavigatorModule.checkPermissionsAndRun(ARSceneNavigatorModule.java:316)
...

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, screen capture, video recording. The more information you provide, the better we can support you.
After following the Windows quick start guide to build the hello world app, add
async _takeScreenshot() {
    await this.props.sceneNavigator.takeScreenshot("viroScreen", true).then((retDict)=>{
      console.log(retDict.success, retDict.url, retDict.errorCode);
    });
  }
AND
this._takeScreenshot = this._takeScreenshot.bind(this);
into HelloWorldSceneAR.js, then call the function from any onClick trigger in either the test bed, or build from Android Studio

**Comment by akshaygpta007** [comment]
Facing the same issue

**Comment by robertobrogi83** [comment]
the same issue.... there is news about that?

**Comment by hrastnik** [comment]
I've had the same problem. The solution is to add the following lines `android/gradle.properties`.

```
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by robertobrogi83** [comment]
@hrastnik thanks a lot! 
with this fix work... the documentation is a nightmare...
Have a nice day

**Comment by zubairKhan-dev** [comment]
async _takeScreenshot() {

        try {
            const granted = await PermissionsAndroid.request(
                PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
                {
                    title: "Access external storage permission",
                    message:
                        "We need permission to external storage " +
                        "so you can take awesome pictures.",
                    buttonNeutral: "Ask Me Later",
                    buttonNegative: "Cancel",
                    buttonPositive: "OK"
                }
            );

            if (granted === PermissionsAndroid.RESULTS.GRANTED) {

                await this._arNavigator.sceneNavigator.takeScreenshot('sgc', false)


            } else {
                console.warn('Camera permission denied');
            }
        } catch (err) {
            console.warn(err);
        }
    }

when this method is invoked, the app crashes. can someone help ?
