### ISSUE TITLE
Android, 2048x1024 HLS/MP4 does not play

### ISSUE THREAD

**Issue by newbot23** [viromedia/viro#99]
Hello guys, 

we have tried to play HLS/MP4 with resolutions like 2048x1024 and up to UHD/4k and they do not play, have got following exception: 

com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(null, null, video/avc, -1, null, [2048, 1024, -1.0], [-1, -1])

We have checked the same stream on the same device in Chrome and it's playable there. 

Curious, what Exoplayer version do you use?
What resolutions have you successfully tested on Android? 

Thanks.

**Comment by dthian** [comment]
Hey @newbot23, currently we are targeting the an older exoplayer version (exoplayer:r2.2.0). We've successfully tested resolutions like 1920x1080. As such I'm wondering if this issue can be resolved by upgrading to a later release. 

To help with the diagnosis, could you provide:
1. A sample HLS/MP4 link with a 2048x1024 and UHD/4k resolution that we can verify and confirm with the bug with? 
2. The Device model, and it's Android OS version the bug occurs on, and it's screen size (if possible).

**Comment by newbot23** [comment]
hi @dthian, thanks for your promt reply. 

1. Here are the links:
https://static-vrticket.cdnvideo.ru/vrticket/bbb_3840x1920.mp4
https://static-vrticket.cdnvideo.ru/vrticket/bbb_2880x1440.mp4
https://static-vrticket.cdnvideo.ru/vrticket/bbb_2048x1024.mp4

2. Devices: 
Redmi 4X, Android 7.1.2
Redmi 4A, Android 6.0.1 
Nexus 7, Android 6.0.1
htc one, android 5.0

let me know please if you need anything else

**Comment by dthian** [comment]
Thanks @newbot23, unfortunately I'm not able to reproduce the crash yet with the links above. Could you send me the full crash stack trace?

**Comment by newbot23** [comment]
Thanks @dthian, will provide the full crash stack trace und build.gradle tomorrow. 
Would you please tell me, do the links play normally?

**Comment by dthian** [comment]
@newbot23, yup the 3 links above plays normally on our devices. 
I've tested so far on an S6 and a Pixel 2 device and verified that the video plays as expected.

**Comment by newbot23** [comment]
@dthian here are the details
full stack trace
`11-27 14:49:43.463 2945-3287/com.example.viro E/ExoPlayerImplInternal: Renderer error.
   com.google.android.exoplayer2.ExoPlaybackException
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:376)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:363)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:770)
       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:341)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:501)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:484)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:464)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)
       at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
    Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(null, null, video/avc, -1, null, [2048, 1024, -1.0], [-1, -1])
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:363) 
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:770) 
       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:341) 
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:501) 
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:484) 
       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:464) 
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300) 
       at android.os.Handler.dispatchMessage(Handler.java:98) 
       at android.os.Looper.loop(Looper.java:154) 
       at android.os.HandlerThread.run(HandlerThread.java:61) 
       at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
    Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
       at android.media.MediaCodec.native_configure(Native Method)
       at android.media.MediaCodec.configure(MediaCodec.java:1778)
       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:327)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:352)
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:770) 
       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:341) 
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readFormat(MediaCodecRenderer.java:501) 
       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:484) 
       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:464) 
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300) 
       at android.os.Handler.dispatchMessage(Handler.java:98) 
       at android.os.Looper.loop(Looper.java:154) 
       at android.os.HandlerThread.run(HandlerThread.java:61) 
       at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)`

build.gradle:
```
def enableProguardInReleaseBuilds = false
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"
    dexOptions {
        jumboMode true
    }
    defaultConfig {
        multiDexEnabled true
        applicationId "com.example.viro"
        minSdkVersion 21
        targetSdkVersion 25
        versionCode 34
        versionName "1.0.34"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    productFlavors {
        gvr {
            resValue 'string', 'app_name', 'VR Ticket'
            buildConfigField 'String', 'VR_PLATFORM', '"GVR"'
        }
        ovr {
            resValue 'string', 'app_name', 'ViroCodeSamples-ovr'
            applicationIdSuffix '.ovr'
            buildConfigField 'String', 'VR_PLATFORM', '"OVR_MOBILE"'
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile project(':react-native-camera')
    compile project(':react-native-orientation')
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:25.0.0'
    compile 'com.facebook.react:react-native:+'
    compile project(':arcore_client')
    compile project(':gvr_common')
    compile project(path: ':react_viro')
    compile project(path: ':viro_renderer')
    compile 'com.google.android.exoplayer:exoplayer:r2.2.0'
    compile 'com.google.protobuf.nano:protobuf-javanano:3.0.0-alpha-7'
    compile 'com.amazonaws:aws-android-sdk-core:2.2.+'
    compile 'com.amazonaws:aws-android-sdk-ddb:2.2.+'
    compile 'com.amazonaws:aws-android-sdk-ddb-mapper:2.2.+'
    compile 'com.amazonaws:aws-android-sdk-cognito:2.2.+'
    compile 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.2.+'
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
```

**Comment by dthian** [comment]
Hi @newbot23, can you also provide the js files representing the 3D scene with the videos that you are trying to view that causes the crash? (Just in case we missed something). Also, were you able to test the video on devices that did work (did play)?

After doing a bit of digging through online, it sounds like the crash may be caused natively by the ExoPlayer itself. There is currently an open [github Exoplayer issue](https://github.com/google/ExoPlayer/issues/2907) that contains the same error code as the ones you have provided in the stack trace (CodecException: Error 0xfffffff4).

In that situation, it looks like **the user is attempting to play multiple video streams on certain Android device models, that results in that error**. This is also further explained in [this](https://github.com/google/ExoPlayer/issues/1286) and [this](https://github.com/google/ExoPlayer/issues/540) github exoplayer issue as well. 

Interesting comments from these issues are:
> 
> not many devices support multiple hardware decoders simultaneously.
> You may consider software decoder.
> 
> device | chipset | work
> -- | -- | --
> Samsung tab 2 7 | TI OMAP 4430 | o
> Samsung S3 | Exynos 4412 Quad | o
> Nexus 7 2nd | Qualcomm S4Pro | x
> Nexus 6 | Qualcomm 805 | x
> 

and also: 

> It sounds like this device does not allow more than one player to be instantiated at a time. In general Android devices don't have to support playing more than one video at a time, and whether it works can also depend on the input videos' formats.

> The Android M CDD (and older versions) do not require compatible devices to support playing more than one video at a time, and I don't think there are any CTS tests that fail if using two video decoders at a time doesn't work.

**Thus, can you confirm:**
1. If you have multiple ViroVideos in your scene that are streaming videos simultaneously (may cause the error).

2. You've mentioned previously that you've also attempted to play the same video in your chrome browser to verify the video. As such, I wonder if you could be in a situation where more than one exo player is being instantiated as well, causing the issue. Can you confirm if this is the case by killing any application that is stream your video except for the viroSample and see if the error still occurs.

**Comment by newbot23** [comment]
Hi @dthian, thanks for your feedback and thorough investigations. 
We use almost identical version of your: https://github.com/viromedia/viro/blob/master/js/ViroMediaPlayer/Viro360Theatre.js
So don't think there is a problem with that. 
1. No, there is no other streams. 
2. Chrome was closed before our test. 
We have activated transcoding for the HLS streams in 1920x1080, and our devices play them normally. So I think it's rather a device connected issue. 
Don't know whether chrome is using Exoplayer and what version exactly, but higher resolution are still playable there. 
Do you have have other test devices, so you could reproduce the issue on your side?

**Comment by dthian** [comment]
"We have activated transcoding for the HLS streams in 1920x1080, and our devices play them normally. So I think it's rather a device connected issue."
- Can you further explain what you mean from the above by activated transcoding for HLS streams? - Does it work for all your videos then once you activated it (the bug no longer repros)?  
- Why do you think it is a device connected issue again?

Unfortunately we were not able to reproduce your issue on our side yet. I've also tried a Nexus 5 with a similar Snap Dragon + Adreno chipset, but cannot reproduce.

**Comment by newbot23** [comment]
Hi @dthian, 
* we have activated backend transcoding, so 4k stream was transcoded to 1080p stream
* we have not tested with all available videos, cause they all use the same codec and settings
* we think it's device connected issue because we have changed only the source and we have got different results. I agree, that it could be code related issue (because the same videos are playable in other players, e.g. chrome browser), but we don't think that it's connected with the code that we are able to change. 

We have prepared a Viro Media based test player, with different resolutions, just for testing purposes: 
https://www.dropbox.com/s/fp3oyoiao6gx9ds/vr-test-app.apk?dl=0 with following resolutions: 
* 1920x960
* 1920x1080
* 2048x1024
* 2880x1440
* 3840x1920

1920x960, 1920x1080 does work on our devices (nexus 7, htc one, redmi 4x), higher resolutions - don't.

**Comment by dthian** [comment]
Hi, @newbot23, thanks for uploading the APK. Unfortunately, I am still unable to reproduce the issue - am still able to play the high resolution videos (3840x1920 / 2880x1440) on our devices (Nexus 5 and S6 phones here).

From the above, as the video playback works without any changes to the ViroPlatform, you are right in saying that it may be an network / video transmission issue. Thus, it sounds like the root cause of your issue is mainly due to the format of which your 4k video is transcoded and then transmitted in, and if your targeted mobile phones has supported hardware/software decoders to preview these video formats of such quality / resolutions. **That is, those devices may not support decoding higher resolution videos, at least with ExoPlayer**

ExoPlayer itself [mentions](https://google.github.io/ExoPlayer/supported-formats.html):

> By default ExoPlayer uses Android’s platform decoders. Hence the supported sample formats depend on the underlying platform rather than on ExoPlayer. Sample formats supported by Android devices are documented [here](https://developer.android.com/guide/topics/media/media-formats.html#core). **Note that individual devices may support additional formats beyond those listed.**".

As such it doesn't sound like a ViroPlatform issue, but instead a limitation of the hardware on a certain Android devices.
